pagopa/selfcare-ms-party-registry-proxy

- .devops/deploy-pipelines.yml
- pom.xml
> Fix-devops

- CODEOWNERS
- app/src/main/resources/swagger/api-docs.json
- connector-api/src/main/java/it/pagopa/selfcare/party/registry_proxy/connector/api/IndexSearchService.java
- connector/lucene/src/main/java/it/pagopa/selfcare/party/registry_proxy/connector/lucene/model/InstitutionEntity.java
- connector/lucene/src/main/java/it/pagopa/selfcare/party/registry_proxy/connector/lucene/reader/CategoryIndexSearchService.java
- connector/lucene/src/main/java/it/pagopa/selfcare/party/registry_proxy/connector/lucene/reader/IndexSearchServiceTemplate.java
- core/src/main/java/it/pagopa/selfcare/party/registry_proxy/core/InstitutionService.java
- core/src/main/java/it/pagopa/selfcare/party/registry_proxy/core/InstitutionServiceImpl.java
- pom.xml
- web/src/main/java/it/pagopa/selfcare/party/registry_proxy/web/controller/InstitutionController.java
- web/src/main/resources/swagger/swagger_en.properties
Works only with L6, L4, L45 categories
> Adding new category filter

- connector/rest/src/main/java/it/pagopa/selfcare/party/registry_proxy/connector/rest/NationalRegistriesConnectorImpl.java
- connector/rest/src/test/java/it/pagopa/selfcare/party/registry_proxy/connector/rest/NationalRegistriesConnectorImplTest.java
add check for VerificationResult null in AdE response
AdE sometimes return verificationCode null in case of false.
try to onboard manually institution with AdE verification Failed
> Fix AdE response

- connector/rest/src/main/java/it/pagopa/selfcare/party/registry_proxy/connector/rest/GeoTaxonomiesConnectorImpl.java
Add fallback for geotax rest client
Sometimes geotx throw exception, we need to have a fallback call
> fix: add fallback for geotax calls

- app/src/main/resources/config/application.yml
- connector-api/src/main/java/it/pagopa/selfcare/party/registry_proxy/connector/exception/BadGatewayException.java
- connector-api/src/main/java/it/pagopa/selfcare/party/registry_proxy/connector/exception/ResourceNotFoundException.java
- connector-api/src/main/java/it/pagopa/selfcare/party/registry_proxy/connector/exception/ServiceUnavailableException.java
- connector/rest/pom.xml
- connector/rest/src/main/java/it/pagopa/selfcare/party/registry_proxy/connector/rest/GeoTaxonomiesConnectorImpl.java
- connector/rest/src/main/java/it/pagopa/selfcare/party/registry_proxy/connector/rest/decoder/FeignErrorDecoder.java
- connector/rest/src/main/resources/config/geo-taxonomies-rest-client.properties
- web/src/main/java/it/pagopa/selfcare/party/registry_proxy/web/handler/PartyRegistryProxyExceptionHandler.java
Add circuitbreaker resilience4j for handling exception on geotax rest client
Sometimes geotax api is unvailable, we need to have a fallback call
> feat: added circuitbreaker for geotax rest client

- CODEOWNERS
Remove from codeowners external contributor
PR approved must be done by internal contributor
> restrict codeowners as selfcare-contributors

- connector-api/src/main/java/it/pagopa/selfcare/party/registry_proxy/connector/model/Station.java
- core/src/main/java/it/pagopa/selfcare/party/registry_proxy/core/StationServiceImpl.java
Modified ID for station object in anac registry
This change was necessary to have same logic in identifier's definition among different registries
I have run microservice locally
> Modified ID for station object in anac registry

- connector/azure_storage/src/main/java/it/pagopa/selfcare/party/connector/azure_storage/AnacDataConnectorImpl.java
- core/src/main/java/it/pagopa/selfcare/party/registry_proxy/core/OpenDataLoader.java
Added condition to filter only stations with empy ipa code for anac registry
> Filtered stations with empty ipa code

- app/src/main/resources/config/application.yml
- connector/rest/src/main/java/it/pagopa/selfcare/party/registry_proxy/connector/rest/GeoTaxonomiesConnectorImpl.java
enable circuit breaker on BadGatewayException
Need a fallback method when get BadGatewayException
> enable circuit breaker on BadGatewayException

- connector/azure_storage/src/main/java/it/pagopa/selfcare/party/connector/azure_storage/model/AnacDataTemplate.java
Update headers for anac csv
This change was requested in order to have headers of csv with correct naming
> Update headers for anac csv

- app/src/main/resources/swagger/api-docs.json
- connector/azure_storage/src/main/resources/config/azure-storage-config.properties
- helm/values.yaml
- web/src/main/java/it/pagopa/selfcare/party/registry_proxy/web/controller/StationController.java
- web/src/main/java/it/pagopa/selfcare/party/registry_proxy/web/model/StationResource.java
- web/src/main/java/it/pagopa/selfcare/party/registry_proxy/web/model/StationsResource.java
- web/src/main/java/it/pagopa/selfcare/party/registry_proxy/web/model/mapper/StationMapper.java
Refactor pdnd's resources in stations/anac resources
> Rename pdnd resources to anac/stations

- connector/lucene/src/main/java/it/pagopa/selfcare/party/registry_proxy/connector/lucene/analysis/StationTokenAnalyzer.java
- connector/lucene/src/main/java/it/pagopa/selfcare/party/registry_proxy/connector/lucene/reader/PDNDIndexSearchService.java
- connector/lucene/src/test/java/it/pagopa/selfcare/party/registry_proxy/connector/lucene/writer/PDNDIndexWriterFactoryTest.java
- connector/lucene/src/test/java/it/pagopa/selfcare/party/registry_proxy/connector/lucene/writer/PDNDIndexWriterServiceTest.java
Fix token analyzer for search in anac stations
This change was necessary to allow case insensitive search in anac stations
I have run microservice locally and tested the api **/stations?search=$value**
> Fix token analyzer for search in anac stations

- .devops/code-review-pipelines.yml
- .devops/deploy-pipelines.yml
- .devops/pnpg-code-review-pipelines.yml
- .devops/pnpg-deploy-pipelines.yml
- Dockerfile
- connector/azure_storage/src/test/java/it/pagopa/selfcare/party/connector/azure_storage/client/AzureBlobClientTest.java
- pom.xml
- updated starter-parent version from 0.0.2 to 0.0.3 for jdk 17 update
- updated pipelines from 1.11 to 1.17
- updated dockerfile image
These updates are necessary as there is a need to upgrade to java 17
- Build was done locally
- the microservice was started locally and some APIs were invoked
> [SELC-3371] feat: update to jdk 17

- .devops/deploy-pipelines.yml
- helm/values-dev.yaml
Set resource requests and limits in deployment manifest
Every pod should run under some limit
> [SELC-3485] Set resource request and limits - DEV

- app/pom.xml
- app/src/main/java/it/pagopa/selfcare/party/registry_proxy/SelfCarePartyRegistryProxyApplication.java
- app/src/main/resources/config/application.yml
- connector-api/pom.xml
- connector-api/src/main/java/it/pagopa/selfcare/party/registry_proxy/connector/api/FTPConnector.java
- connector-api/src/main/java/it/pagopa/selfcare/party/registry_proxy/connector/api/IndexWriterService.java
- connector-api/src/main/java/it/pagopa/selfcare/party/registry_proxy/connector/model/AnacDataTemplate.java
- connector/azure_storage/src/main/java/it/pagopa/selfcare/party/connector/azure_storage/AnacDataConnectorImpl.java
- connector/azure_storage/src/test/java/it/pagopa/selfcare/party/connector/azure_storage/AnacDataConnectorImplTest.java
- connector/ftp/pom.xml
- connector/ftp/src/main/java/it/pagopa/selfcare/party/connector/ftp/AnacDataFromFTPConnectorImpl.java
- connector/ftp/src/main/java/it/pagopa/selfcare/party/connector/ftp/client/AnacFTPClient.java
- connector/ftp/src/main/resources/config/ftp-config.properties
- connector/ftp/src/test/java/it/pagopa/selfcare/party/connector/ftp/AnacDataFromFTPConnectorImplTest.java
- connector/ftp/src/test/java/it/pagopa/selfcare/party/connector/ftp/client/FTPClientTest.java
- connector/lucene/src/main/java/it/pagopa/selfcare/party/registry_proxy/connector/lucene/writer/IndexWriterServiceTemplate.java
- connector/lucene/src/test/java/it/pagopa/selfcare/party/registry_proxy/connector/lucene/writer/DummyAOOIndexWriterService.java
- connector/lucene/src/test/java/it/pagopa/selfcare/party/registry_proxy/connector/lucene/writer/DummyCategoryIndexWriterService.java
- connector/lucene/src/test/java/it/pagopa/selfcare/party/registry_proxy/connector/lucene/writer/DummyInstitutionIndexWriterService.java
- connector/lucene/src/test/java/it/pagopa/selfcare/party/registry_proxy/connector/lucene/writer/DummyUOIndexWriterService.java
- connector/lucene/src/test/java/it/pagopa/selfcare/party/registry_proxy/connector/lucene/writer/StationIndexWriterServiceTest.java
- connector/pom.xml
- core/src/main/java/it/pagopa/selfcare/party/registry_proxy/core/ANACService.java
- core/src/main/java/it/pagopa/selfcare/party/registry_proxy/core/ANACServiceImpl.java
- core/src/main/java/it/pagopa/selfcare/party/registry_proxy/core/OpenDataLoader.java
- core/src/test/java/it/pagopa/selfcare/party/registry_proxy/core/ANACServiceImplTest.java
- core/src/test/java/it/pagopa/selfcare/party/registry_proxy/core/OpenDataLoaderTest.java
- helm/pnpg/templates/deployment.yaml
- helm/templates/deployment.yaml
- pom.xml
- added sftp connection to retrieve ANAC csv
- added scheduled job to update ANAC index
- In order to avoid manual upload of anac csv file on azure storage, we have to retrieve it from ftp.
> [SELC-3487][SELC-3488]

- .github/workflows/release_open_api.yml
Update step for check breaking changes into github action
Changed action to retrieve breaking changes into api-docs.
> [SELC-3516] bug: update step for check breaking changes into github action

- helm/values-dev.yaml
Increase replicas to 2 in dev
You can test things without donwtime
> [SELC-3607] Increase replicas - DEV

- helm/values-dev.yaml
- pom.xml
> Release UAT

- .github/workflows/pr_release_ms_pnpg.yml
- pom.xml
Add workflow
Add sonar host
Migration to container apps
> [EC-156] Add pnpg release workflow

- web/src/main/java/it/pagopa/selfcare/party/registry_proxy/web/filter/LogFilter.java
> ops: disable log health check

- infra/container_apps/env/dev-pnpg/terraform.tfvars
- infra/container_apps/env/dev/terraform.tfvars
- infra/container_apps/env/prod-pnpg/terraform.tfvars
- infra/container_apps/env/prod/terraform.tfvars
- infra/container_apps/env/uat-pnpg/terraform.tfvars
- infra/container_apps/env/uat/terraform.tfvars
JWT_TOKEN_PUBLIC_KEY misses as env variable
> [EC-125] fix: added JWT_TOKEN_PUBLIC_KEY as secret

- infra/container_apps/apim.tf
- infra/container_apps/apim_api_bff_proxy.json
* Remove api unused by frontend
* Move api bff json to infra folder
Some endpoints are not used by frontend. In addition, these api must be limited to internal service backend only.
> chore: remove api bff proxy unused by frontend

- .github/workflows/pr_ms.yml
- .github/workflows/release_ms.yml
- .github/workflows/release_ms_pnpg.yml
- infra/container_apps/README.md
- infra/container_apps/apim.tf
- infra/container_apps/env/dev-pnpg/terraform.tfvars
- infra/container_apps/env/dev/terraform.tfvars
- infra/container_apps/env/prod/terraform.tfvars
- infra/container_apps/env/uat-pnpg/terraform.tfvars
- infra/container_apps/env/uat/terraform.tfvars
- infra/container_apps/locals.tf
- infra/container_apps/main.tf
- infra/container_apps/variables.tf
* Container App env name must be specified
* workload_profile null for dev and prod
Container App env could have a different configuration among dev or uat or prod.
> chore: Migration to Container App module with name and workload_profile empty

- infra/container_apps/README.md
- infra/container_apps/env/uat-pnpg/terraform.tfvars
- infra/container_apps/env/uat/terraform.tfvars
- infra/container_apps/locals.tf
- infra/container_apps/main.tf
- infra/container_apps/variables.tf
Using terraform ca module with suffix
Change cae url uat
Migration uat env with -001 suffix
> chore: Migration uat using terraform ca module with suffix

- infra/container_apps/main.tf
Added initialDelaySeconds to startup health check so it will start checking after 60 seconds
Startup take a lot of time for this microservice causing trigger alert for microservice not readiness.
> chore: added initialDelaySeconds to startup health check

- app/src/main/resources/swagger/api-docs.json
- connector/lucene/src/main/java/it/pagopa/selfcare/party/registry_proxy/connector/lucene/converter/InsuranceCompanyToDocumentConverter.java
- core/src/main/java/it/pagopa/selfcare/party/registry_proxy/core/IvassServiceImpl.java
> Fix find by tax code

- connector/lucene/src/main/java/it/pagopa/selfcare/party/registry_proxy/connector/lucene/reader/IndexSearchServiceTemplate.java
Adding try catch to avoid error not detected
> [SELC-4850] fix: 500 error when search Institutions with 3 chars

- .github/workflows/release_open_api.yml
- app/src/main/resources/swagger/api-docs.json
Using a common GitHub Action designed to facilitate the detection of conflicts in Swagger documentation files
> ops: GitHub Action to detect breaking changes on Swagger

- connector/rest/docs/openapi/pdnd-v2.json
- connector/rest/pom.xml
- connector/rest/src/main/java/it/pagopa/selfcare/party/registry_proxy/connector/rest/client/PdndRestClient.java
- connector/rest/src/main/java/it/pagopa/selfcare/party/registry_proxy/connector/rest/config/PdndClientConfig.java
- connector/rest/src/main/resources/config/pdnd-rest-client.properties
- infra/container_apps/env/dev-pnpg/terraform.tfvars
- infra/container_apps/env/dev/terraform.tfvars
- infra/container_apps/env/prod-pnpg/terraform.tfvars
- infra/container_apps/env/prod/terraform.tfvars
- infra/container_apps/env/uat-pnpg/terraform.tfvars
- infra/container_apps/env/uat/terraform.tfvars
added PDND rest client and configs
local env
> [SELC-5177] feat: added PDND rest client and configs

- connector/rest/src/main/java/it/pagopa/selfcare/party/registry_proxy/connector/rest/model/PDNDImpresa.java
- connector/rest/src/main/java/it/pagopa/selfcare/party/registry_proxy/connector/rest/model/mapper/PDNDBusinessMapper.java
- web/src/main/java/it/pagopa/selfcare/party/registry_proxy/web/controller/PDNDInfoCamereController.java
Updated mapper to set city, county and zipCode
In order to give in response such fields, the mapper has been changed with right mappings configuration
I have run ms locally and tested the api for PDNDInfocamere
> [SELC-5176] feat: Updated mapper to set city, county and zipCode

- infra/container_apps/apim_api_bff_proxy.json
- added PDND infocamere API to APIM
the API has been exposed on the APIM to allow the FE to invoke it
the API was invoked through APIM to verify its correct functioning
> [SELC - 5298] feat: added PDND infocamere API to APIM

- infra/container_apps/README.md
- infra/container_apps/env/dev/terraform.tfvars
- infra/container_apps/env/prod/terraform.tfvars
> chore: Move to Container App Env workload PROD

- app/src/main/resources/config/application.yml
- infra/container_apps/env/dev-pnpg/terraform.tfvars
- infra/container_apps/env/dev/terraform.tfvars
- infra/container_apps/env/prod-pnpg/terraform.tfvars
- infra/container_apps/env/prod/terraform.tfvars
- infra/container_apps/env/uat-pnpg/terraform.tfvars
- infra/container_apps/env/uat/terraform.tfvars
Added Ivass base path config and set config for ivass rest connector
With these configurations you will leverage the connector rest by retrieving the ivass csv from an api and not from azure storage
> [SELC-4840] feat: added Ivass base path config and set config for ivass rest connector

- app/src/main/resources/swagger/api-docs.json
- core/src/main/java/it/pagopa/selfcare/party/registry_proxy/core/IvassService.java
- core/src/main/java/it/pagopa/selfcare/party/registry_proxy/core/IvassServiceImpl.java
- core/src/test/java/it/pagopa/selfcare/party/registry_proxy/core/IvassServiceImplTest.java
- web/src/main/java/it/pagopa/selfcare/party/registry_proxy/web/controller/IvassController.java
- web/src/test/java/it/pagopa/selfcare/party/registry_proxy/web/controller/IvassControllerTest.java
removed deprecated api for IVASS search by taxCode
> [SELC-5587] feat: removed deprecated api for IVASS search by taxCode

- core/src/main/java/it/pagopa/selfcare/party/registry_proxy/core/NationalRegistriesServiceImpl.java
- core/src/test/java/it/pagopa/selfcare/party/registry_proxy/core/NationalRegistriesServiceImplTest.java
This PR mitigate an malformed response from InfoCamere that has modified the timestamp value
> hotfix: Disable check timestamp not Null on return Business list

- core/src/main/java/it/pagopa/selfcare/party/registry_proxy/core/AOOServiceImpl.java
- core/src/main/java/it/pagopa/selfcare/party/registry_proxy/core/UOServiceImpl.java
- core/src/test/java/it/pagopa/selfcare/party/registry_proxy/core/AOOServiceImplTest.java
added scheduler for AOO IPA index
a scheduler has been added so that at 2 AM of each day the IPA index of the AOOs is rescheduled
the MS was started locally and a time close to the current one was set to verify that the scheduler was triggered
> [SELC-1548] feat: added scheduler for AOO IPA index

- .opex/api-selfcare-party-registry-proxy/env/dev/backend.ini
- .opex/api-selfcare-party-registry-proxy/env/dev/backend.tfvars
- .opex/api-selfcare-party-registry-proxy/env/dev/config.yaml
- .opex/api-selfcare-party-registry-proxy/env/dev/terraform.tfvars
> [SELC-5311] feat: Added Opex dashboard (dev)

- .github/workflows/opex_api.yml
> [SELC-5311] feat: Added github action for opex

- core/src/main/java/it/pagopa/selfcare/party/registry_proxy/core/InstitutionServiceImpl.java
- core/src/test/java/it/pagopa/selfcare/party/registry_proxy/core/InstitutionServiceImplTest.java
added scheduler for Institutions IPA index
a scheduler has been added so that at 2 AM of each day the IPA index of the Institutions is rescheduled
the MS was started locally and a time close to the current one was set to verify that the scheduler was triggered
> [SELC - 1547] feat: added scheduler for Institutions IPA index

- app/src/main/resources/swagger/api-docs.json
- web/src/main/java/it/pagopa/selfcare/party/registry_proxy/web/controller/NationalRegistriesController.java
feat: Added Tag support-pnpg to legalAddress API
> [PNPG-241] feat: Added Tag support-pnpg to legalAddress API

- app/src/main/resources/swagger/api-docs.json
- web/src/main/java/it/pagopa/selfcare/party/registry_proxy/web/controller/InfoCamereController.java
Added Tag support-pnpg to institutionsByLegalTaxId API
> [PNPG-240] feat: Added Tag support-pnpg to institutionsByLegalTaxId API

- .github/workflows/opex_api.yml
> fix: Environment on opex action

- core/src/main/java/it/pagopa/selfcare/party/registry_proxy/core/InstitutionServiceImpl.java
- core/src/test/java/it/pagopa/selfcare/party/registry_proxy/core/InstitutionServiceImplTest.java
- web/src/main/java/it/pagopa/selfcare/party/registry_proxy/web/controller/InstitutionController.java
- web/src/test/java/it/pagopa/selfcare/party/registry_proxy/web/controller/InstitutionControllerTest.java
Set default value to ORIGIN to IPA on institution/cf api
When searching for institution IPA origin was used as optional value.
> Set default value to ORIGIN

- app/src/main/resources/swagger/api-docs.json
- web/src/main/java/it/pagopa/selfcare/party/registry_proxy/web/controller/PDNDInfoCamereController.java
added tag internal-v1 to API:
- POST: /infocamere-pdnd/institution/{taxCode}
> [SELC-5962] feat: added tag internal-v1 to PDND-infocamere

- infra/container_apps/env/uat-pnpg/terraform.tfvars
- infra/container_apps/env/uat/terraform.tfvars
> [SALC-6134] Adding new scale rule for UAT

- app/src/main/resources/swagger/api-docs.json
- app/src/test/java/it/pagopa/selfcare/party/registry_proxy/web/config/SwaggerConfigTest.java
- pom.xml
- web/pom.xml
Updated pom version for spring doc web-ui
In order to have a clean pom, duplicated dependencies with artifact id **springdoc-openapi-starter-webmvc-ui** have been deleted and moved to root pom.xml
> [SELC-5821] fix: Updated pom version for spring doc web-ui

- app/src/main/resources/swagger/api-docs.json
- pom.xml
> Updated selc-commons references

- app/src/main/resources/swagger/api-docs.json
- app/src/test/java/it/pagopa/selfcare/party/registry_proxy/web/config/SwaggerConfigTest.java
- connector/rest/src/main/java/it/pagopa/selfcare/party/registry_proxy/connector/rest/client/GeoTaxonomiesRestClient.java
- connector/rest/src/main/java/it/pagopa/selfcare/party/registry_proxy/connector/rest/client/NationalRegistriesRestClient.java
- connector/rest/src/main/java/it/pagopa/selfcare/party/registry_proxy/connector/rest/config/ApiKeyRequestInterceptor.java
- connector/rest/src/main/java/it/pagopa/selfcare/party/registry_proxy/connector/rest/config/GeoTaxonomiesRestClientConfig.java
- connector/rest/src/main/java/it/pagopa/selfcare/party/registry_proxy/connector/rest/config/NationalRegistriesRestClientConfig.java
- connector/rest/src/test/java/it/pagopa/selfcare/party/registry_proxy/connector/rest/config/ApiKeyRequestInterceptorTest.java
Added check on header client in order to avoid overrding values
This check has been added to avoid override into map of headers
> Fix request interceptor

- app/src/main/resources/swagger/api-docs.json
- connector-api/src/main/java/it/pagopa/selfcare/party/registry_proxy/connector/model/AOO.java
- connector-api/src/main/java/it/pagopa/selfcare/party/registry_proxy/connector/model/UO.java
- connector-api/src/test/java/it/pagopa/selfcare/party/registry_proxy/connector/model/DummyAOO.java
- connector-api/src/test/java/it/pagopa/selfcare/party/registry_proxy/connector/model/DummyUO.java
- connector/lucene/src/main/java/it/pagopa/selfcare/party/registry_proxy/connector/lucene/converter/AOOToDocumentConverter.java
- connector/lucene/src/main/java/it/pagopa/selfcare/party/registry_proxy/connector/lucene/converter/UOToDocumentConverter.java
- connector/lucene/src/main/java/it/pagopa/selfcare/party/registry_proxy/connector/lucene/model/AOOEntity.java
- connector/lucene/src/main/java/it/pagopa/selfcare/party/registry_proxy/connector/lucene/model/UOEntity.java
- connector/lucene/src/test/java/it/pagopa/selfcare/party/registry_proxy/connector/lucene/model/DummyAOO.java
- connector/lucene/src/test/java/it/pagopa/selfcare/party/registry_proxy/connector/lucene/model/DummyUO.java
- connector/rest/src/main/java/it/pagopa/selfcare/party/registry_proxy/connector/rest/model/IPAOpenDataAOOTemplate.java
- connector/rest/src/main/java/it/pagopa/selfcare/party/registry_proxy/connector/rest/model/IPAOpenDataUOTemplate.java
- web/src/main/java/it/pagopa/selfcare/party/registry_proxy/web/model/AOOResource.java
- web/src/main/java/it/pagopa/selfcare/party/registry_proxy/web/model/UOResource.java
- web/src/main/java/it/pagopa/selfcare/party/registry_proxy/web/model/mapper/AOOMapper.java
- web/src/test/java/it/pagopa/selfcare/party/registry_proxy/web/model/DummyAOO.java
- web/src/test/java/it/pagopa/selfcare/party/registry_proxy/web/model/DummyUO.java
added mapping for reading from csv of other fields related to contacts
added logic that in case of non-match with pec address return inidirizzo if present in subsequent columns
> [SELC-6432]: feat: Added check on contact field

- app/src/main/resources/swagger/api-docs.json
- web/src/main/java/it/pagopa/selfcare/party/registry_proxy/web/config/SwaggerConfig.java
- web/src/main/resources/swagger/swagger_en.properties
> [SELC-6728] fix: Fixed method of configuration of swagger

- app/src/main/resources/swagger/api-docs.json
- web/src/main/java/it/pagopa/selfcare/party/registry_proxy/web/controller/AOOController.java
- web/src/main/java/it/pagopa/selfcare/party/registry_proxy/web/controller/InstitutionController.java
- web/src/main/java/it/pagopa/selfcare/party/registry_proxy/web/controller/UOController.java
- added tag to expose IPA api to internal group
APIs have been exposed in the internal apim group to allow SM to use them
> [SELC-6690] feat: added tag to expose IPA api to internal group

- app/src/main/resources/swagger/api-docs.json
- web/src/main/java/it/pagopa/selfcare/party/registry_proxy/web/controller/InstitutionController.java
- removed tag from institution controller
> [SELC-6690] fix: removed tag from institution controller

- app/src/main/resources/swagger/api-docs.json
- web/src/main/java/it/pagopa/selfcare/party/registry_proxy/web/controller/PDNDInfoCamereController.java
> fix: updated operation id for PDND infocamere APIs

- app/src/main/resources/swagger/api-docs.json
- web/src/main/java/it/pagopa/selfcare/party/registry_proxy/web/config/SwaggerConfig.java
Updated configuration of swagger doc
This change allows us to use swagger to check APIs
> Fix swagger UI

- app/src/main/resources/swagger/api-docs.json
- connector-api/src/main/java/it/pagopa/selfcare/party/registry_proxy/connector/model/nationalregistriespdnd/PDNDBusiness.java
- connector/rest/src/main/java/it/pagopa/selfcare/party/registry_proxy/connector/rest/model/mapper/PDNDBusinessMapper.java
- connector/rest/src/main/java/it/pagopa/selfcare/party/registry_proxy/connector/rest/model/visura/DatiIdentificativiImpresa.java
- web/src/main/java/it/pagopa/selfcare/party/registry_proxy/web/model/PDNDBusinessResource.java
Added into response fields to pdnd client
local - dev
> [SELC-7388] feat: Added new fields to pdnd to retrieve the legal nature of the entity and vatnumber

- app/src/main/resources/swagger/api-docs.json
- web/src/main/java/it/pagopa/selfcare/party/registry_proxy/web/controller/PDNDVisuraInfoCamereController.java
Fixed swagger for get visura document API
> Fixed swagger for get visura document API

- app/src/main/resources/config/application.yml
- connector/ftp/src/main/resources/config/ftp-config.properties
Fix source for anac data download: from sftp to azure storage
This change is necessary to avoid data vulnerabilities on file uploaded through sftp
> Fix source for anac data download

- app/src/main/resources/config/application.yml
- connector/azure_storage/src/main/java/it/pagopa/selfcare/party/connector/azure_storage/AnacDataConnectorImpl.java
- connector/ftp/src/main/resources/config/ftp-config.properties
- infra/container_apps/env/dev/terraform.tfvars
- infra/container_apps/env/prod/terraform.tfvars
- infra/container_apps/env/uat/terraform.tfvars
Added env into infra and updated config
> fix: Updated infra added env for anac FTP mode

- infra/container_apps/env/dev/terraform.tfvars
- infra/container_apps/env/prod/terraform.tfvars
- infra/container_apps/env/uat/terraform.tfvars
Added references for secret to encrypt/decrypt visura document
The added secrets will be used to encrypt all document retrieved from PDND Infocamere before uploading it into Azure storage
> [SELC-7764] feat: added references for secret to encrypt/decrypt visura document
